### ISSUE TITLE
Meetup - Polkadot - London, UK

### ISSUE THREAD

**Issue by jplatts12** [w3f/General-Grants-Program#1]
[London meetup.com group](https://www.meetup.com/Polkadot-London/events/252230181/)

**Comment by jplatts12** [comment]
[Meetup.com London group](https://www.meetup.com/Polkadot-London/events/252230181/)

[Latest meetup](https://www.meetup.com/Polkadot-London/events/252230181/) - 12 July, 2018

**Comment by Cambrial** [comment]
Hey guys,

I'd love to help run the Polkadot meetup in London if you're still looking for event partners! Let me know if that's the case :)

**Comment by Josh0akley** [comment]
Hey Cambrial,

That would be ace. Feel free to drop me a line and we can fix a time to chat. We are provisionally booked for our next event on October 3rd. Details to be announced this week on meetup.com

My email is: joshua@web3.foundation

**Comment by EdwardAThomson** [comment]
The second meetup for Polkadot London has been announced:

## Fabric, Fern, Finality Gadgets & Substrate
Web3 Foundation welcomes you to the second edition of Polkadot - London!

We are excited to be be back in town and are bringing with us some core members of the Polkadot team as well as some prominent local guest speakers.

**Date**: Wednesday, October 3, 2018
**Time**: 6:30 PM t\o 9:00 PM
**Venue**: Second Home, 68 Hanbury Street London, E1 5JL · London


https://www.meetup.com/Polkadot-London/events/254240112/

**Comment by jplatts12** [comment]
Polkadot London v3 was a success: Check out the videos here: https://www.meetup.com/Polkadot-London/events/254945879/
