### ISSUE TITLE
Meetup - Polkadot - Atlanta, GA, USA

### ISSUE THREAD

**Issue by taggartbg** [w3f/General-Grants-Program#107]
After running the React meetup in Atlanta since July 2015, I have passed the torch and am looking to start a Polkadot meetup hosted at the same meetup space / code school, General Assembly.  I have a commitment from them to support the meetup alongside the support of blockchain venture studio, [Thesis](https://thesis.co). 

What is the plan:
- **Number of people on your team:**
  - 3
- **Do you need help from W3F:**
  - *Financial sponsorship for food, suggested / provided content*
- **Do you need help from the community:**
  - *Support materials, discussions / suggestions, get the word out*

Every month, a community member will present news of the last month in the space.  Following that, a technical presentation will provide context for further community discussion.  Food will be provided.

**Comment by burdges** [comment]
Just fyi, I'm from Atlanta so I pass through a couple times per year.  I'll turn up at one if possible.

**Comment by Web3Foundation** [comment]
@taggartbg could you please apply through this https://polkadot.network/launching-worldwide-polkadot-web3-community-meetups/ application; we'll be glad to help support you out of Atlanta.

**Comment by burdges** [comment]
I'm tentatively planning to visit Atlanta in September or October btw.

**Comment by Web3Foundation** [comment]
Great! Please keep me posted as the idea develops!

Lindsay
