### ISSUE TITLE
Meetup - Substrate - Kyiv, Ukraine

### ISSUE THREAD

**Issue by siman** [w3f/General-Grants-Program#108]
![image](https://user-images.githubusercontent.com/153928/57658928-35166280-75e9-11e9-800c-d436ebc7bb02.png)

Hi, my name is Alex Siman and recently I [attended the Sub0](https://www.youtube.com/watch?v=hsskPkKeqPc)  conference in Berlin. There I talked with Jack and Peter from Web3 Foundation and we discussed the opportunity to hold Substrate workshop in Ukraine.

## What is the plan

We are planning to have a series of events dedicated to Substrate/Polkadot in Kyiv, Ukraine.

### Event # 1 (June 14) ✅ [DONE]

The first event is a meetup called "Hello Substrate" (June 14). I'm going to spread the word about Substrate, Polkadot and W3 foundation,  provide an introduction part and answer questions. We expect between 20 to 40 attendees at this meetup.

We announced the event on several sites:
* https://www.meetup.com/Polkadot-Ukraine/events/261826623/
* https://web.facebook.com/events/872251823128606/
* https://dou.ua/calendar/27351/
* https://ain.ua/event/hello-substrate/
* https://2event.com/en/events/1741144
* https://www.eventbrite.com/e/hello-substrate-parity-tickets-63169124552

UPD: Photo report from the first meetup:

https://medium.com/dappforce/first-substrate-polkadot-meetup-in-kyiv-ukraine-1a5330ef456a

### Event # 2 (mid of July)

Thereafter, in a month (July 20) it would be a good idea to organize a full day meetup (or even two-day meetup) with several presentations of Polkadot, Substrate and its ecosystem. Q&A session and a workshop/hackathon would be a great addition to this meetup. But this depends on the interest of the local community to the first event. 

It would really help us out if representatives of Parity/Web3 Foundation join such an event, speak and take part in QA session. We expect between 40 to 80 attendees at this meetup.

## The team

[**Alex Siman**](https://www.linkedin.com/in/alexsiman/) is a Founder of “Polkadot Ukraine” and a blockchain developer at [Joystream.org](https://www.joystream.org/) – a user-governed video platform built on top of Substrate. He has been building complex web apps since 2008. In 2017 he started to write smart contracts on Solidity and integrate them with dapps. And since 2019 he has been [developing Substrate modules](https://github.com/Joystream/substrate-node-joystream/commits?author=siman) and building a custom UI for these modules by [extending Polkadot Apps](https://github.com/Joystream/apps/commits?author=siman).

[**Anna Yakimets**](https://www.linkedin.com/in/anna-yakimets-61021a119) is a Strategic Partnerships Manager with experience in international PR and media relations management. She has proficiency in organizing various events in innovation businesses about Europe, running IT schools, doing PR in Blockchain startups and interviewing more than 100 Blockchain influencers and Tech Entrepreneurs.

## Do you need help from W3F

For both events, we’d love to get swag (T-shirts and stickers) and information support in your social channels. 

### Event # 1

The first event we can do single-handedly.

### Event # 2

We plan to enhance audience engagement that is why your support/funding and participation in giving talks will play a substantial role at this event. As a lot of different topics on Substrate/Polkadot can be discussed with the effective workshop, we would like to give a warm welcome for Parity team members.

## Do you need help from the community

Help with promotion would be great, plus we would love for as many people as possible to attend.

## Community links

- https://t.me/PolkadotUkraine
- https://www.meetup.com/Polkadot-Ukraine/
- https://www.facebook.com/PolkadotUkraine

## Partners

[BUIDL_ua](http://buidl.in.ua) is a community for blockchain developers in Ukraine. Doing regular meetups to connect teams, exchange expertise and buidl more and better blockchain products.

**Comment by ljg583** [comment]
Hi Alex, 

Thank you for providing such detailed information on your upcoming events.  We would love to support you and your growing community.  Please reach out to me at Lindsay@web3.foundation so we may discuss details and get some merchandise to your first event.

**Comment by siman** [comment]
Hi @ljg583, just sent you a letter to Lindsay@web3.foundation

**Comment by johntrainor** [comment]
Hi Alex, 

Hope you’re well!

I’m working on getting some t-shirts sent to the Substrate workshop, but we’re facing an issue with making a payment. 

By any chance do you have Privat24? I’m wondering if you may be able to cover the payment, and the Web3 Foundation will reimburse you for the expenses. The total is 10576 UAH. 

Please let me know if this is possible! If so, you can send the invoice to:

Web 3.0 Technologies Foundation
Reiffergässli 4
6300, Zug
Switzerland
UID / VAT ID: CHE-322.596.347

Also, if you could let me know your email address, I can loop you in to our conversation with the t-shirt printer. 


Thanks,
John

**Comment by siman** [comment]
Hi John,

Yes, I have Privat24 and can cover the payment.
Here is my email: aleksandr.siman@gmail.com

**Comment by johntrainor** [comment]
Thank you!

**Comment by siman** [comment]
Have announced the first event on several sites:
* https://www.meetup.com/Substrate-Ukraine/events/261826623/
* https://web.facebook.com/events/872251823128606/
* https://dou.ua/calendar/27351/
* https://ain.ua/event/hello-substrate/

**Comment by siman** [comment]
Here is a screencast from Substrate Ukraine Meetup #1 (in Russian)
https://youtu.be/cvgadAHzFww

**Comment by siman** [comment]
Photo report from the first meetup (July 14, 2019, Kyiv, Ukraine):
https://medium.com/dappforce/first-substrate-polkadot-meetup-in-kyiv-ukraine-1a5330ef456a

**Comment by leenpaws** [comment]
please stop spamming emails
