### ISSUE TITLE
Meetup - Polkadot - Shenzhen, China

### ISSUE THREAD

**Issue by ansonla3** [w3f/General-Grants-Program#109]
Hi, I am Anson based in HK, (@toxotguo) one of the team members from Chainx & me would like to organize polkadot meetup together to push Polkadot adoption in China. 

## What is the plan
the first meetup would be between 8 and 15 June (the exact date is not confirmed yet).

## How many people: 
50-70 Would be a good start.

## Do you need help from the community
Help with promotion would be great, plus we would love for as many people as possible to attend.

## Meetup Page
https://www.meetup.com/Polkadot-Shenzhen/

**Comment by jimmychu0807** [comment]
@ansonla3 let me know if you are doing more meetup in HK / SZ, and I will see how I can help.

**Comment by ansonla3** [comment]
let's keep in touch :)
