### ISSUE TITLE
Development: Create new parachains for Polkadot

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#11]
We would like to invite teams to discuss developing new parachains for Polkadot.

## Parachains introduction
The following links will be useful reading for starting to understand what parachains are and how to implement them:
* "[Polkadot:  the parachain](https://medium.com/polkadot-network/polkadot-the-parachain-3808040a769a)" - a blog by Robert Habermeier.
* [Preparing to build on Polkadot](https://medium.com/polkadot-network/preparing-to-build-on-polkadot-349ff5002885) - a blog mainly focussed on building parachains

Implementing a parachain is not likely to be a simple task, but it should get easier over time as more examples and more documentation become available.

To implement a parachain, developers need to implement a state transition validation function, decide upon a state format, and a transaction pooling mechanism. Once you’ve implemented your parachain, there are a couple of extra steps involved in integrating it with Polkadot. To do this you will need to deploy the state transition validation function onto the Relay Chain, then distribute a collator node client that includes the transaction pooling mechanism.

Creating all of these pieces requires thinking about how a collator node should construct the blocks of your chain and how the validity of these blocks can be checked and confirmed by a validator node. There are two options here: (1) write the collator node from scratch, or (2) use a shell collator node that can run different kinds of state machines. At the time of writing, we don’t have the specs for writing a collator node, although more details will be forthcoming as more PoCs are release.

## Substrate
We expect many parachains will be built on Substrate; however, a parachain could also be built from scratch.

For more information on Substrate, please see the following links:

### Web3 Wiki
* [Substrate](https://github.com/w3f/Web3-wiki/wiki/Substrate)

### Presentations
* Gavin Wood presents Parity Substrate at [EventHorizon18](https://www.youtube.com/watch?v=iUMZyL5kTwc), 
The slides: [Slides.com](https://slides.com/paritytech/paritysubstrate#/)
* Robert Habermeier also presented Parity Substrate at the [Berlin Truebit Meetup](https://www.youtube.com/watch?v=q1zLHO7Lkuk).

### Blogs
* "[What is Substrate?](https://medium.com/paritytech/what-is-substrate-29af4231d7e0)" Jack Fransham explains.
* "[Substrate in a nutshell](https://medium.com/paritytech/substrate-in-a-nutshell-a54cd34c7863)" by Dmitriy Kashitsyn.
* "[Substrate testnet launched](https://www.parity.io/substrate-testnet-launched/)" by Phil Lucsok.
* "[Launch a blockchain in minutes with Substrate](https://medium.com/paritytech/launch-a-blockchain-in-minutes-with-substrate-arriving-november-2018-a6e7102ae54a)" by Phil Lucsok.

### Tutorials
* [Creating a custom Substrate chain](https://substrate.readme.io/docs/creating-a-custom-substrate-chain)
* [Deploying a Substrate Node chain](https://substrate.readme.io/docs/deploying-a-substrate-node-chain)
* [How to build a Custom Substrate Module from scratch (Community blog)](https://gitlab.com/chrisdcosta/basictest/blob/master/Howto.md)

### Blockchains using Substrate Today
* [Polkadot](https://github.com/paritytech/polkadot) - Polkadot Relaychain implementation.
* [Shasper](https://github.com/paritytech/shasper) - Ethereum 2.0 beacon chain implementation.
* [ChainX](https://github.com/chainx-org/ChainX) - cross-chain digital asset management platform.
* [Edgeware](http://edgewa.re/) - incentivised testnet for active governance.

## Parachain Collaboration Form
Please provide further details by filling out the following form:

[Link](https://docs.google.com/forms/d/e/1FAIpQLSf5wHgw3KOj_2lg9_dndtX3YkYj59sP7iJ77k4qkD09Q-e6LQ/viewform)

**Comment by anjj123** [comment]
We've been exploring this too, and it ties in with our other focus areas.

**Comment by inthestorm** [comment]
I am new to polkadot project and attracted heavy by its interoperability. I want a try

**Comment by jiangfuyao** [comment]
I want to start learning from the basic parachain and start a grand parachain.

**Comment by agryaznov** [comment]
I'd like to play with the Substrate framework to create new chains

**Comment by tucsonblockchain** [comment]
http://bitcoinmacroeconomics.com/2018/07/22/tucson-arizona-ethereum-ecosystem/ Definitely interested in helping and am interested in establishing Polkadot hub here in Tucson if anybody wants to come visit part time or long term for work / life balance. Let me know I can help further with project or help guide as I learn. Thx

**Comment by yuelipeng** [comment]
We want to build a decentralized exchange based  on substrate，and this DEX will connecting to polkadot as a parachain。

**Comment by EdwardAThomson** [comment]
I've updated the original post with more details on parachains. I've also created a collaboration form that I'd like people to fill out. I realise that it isn't enough to just note your interest but you should also give some indication of what you are planning.

**Comment by tucsonblockchain** [comment]
Set up Polkadot NOOBS Watercooler https://riot.im/app/#/room/!zqIrlPQHNBkzZAICka:matrix.org  and also https://appear.in/polkadotnoobs PolkadotNOOBS (audio and video) for purpose of study group tp learn as we go, in collaboration and for civil discourse.

**Comment by ttmc** [comment]
@tucsonblockchain When I click on that riot.im link, and then click to join the discussion, I get "Failed to join room. You are not invited to this room."

**Comment by EdwardAThomson** [comment]
### Blockchains using Substrate Today
* [Polkadot](https://github.com/paritytech/polkadot) - Polkadot Relaychain implementation.
* [Shasper](https://github.com/paritytech/shasper) - Ethereum 2.0 beacon chain implementation.
* [ChainX](https://github.com/chainx-org/ChainX) - cross-chain digital asset management platform.
* [Edgeware](http://edgewa.re/) - incentivised testnet for active governance.

**Comment by EdwardAThomson** [comment]
This issue is a candidate for our grants program. For details on how to apply, see your grants page: https://grants.web3.foundation

**Comment by burrrata** [comment]
Daonut Protocol grant submitted! 🍩
- https://github.com/w3f/Web3-collaboration/pull/70
