### ISSUE TITLE
Hardware wallet support for Polkadot

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#14]
We would like to invite teams to discuss providing hardware wallet support for Polkadot.

**Comment by burdges** [comment]
I'd think HSMs sounds like a higher priority actually.

**Comment by EdwardAThomson** [comment]
Yeah, we are interested in HSMs for the use cases you are talking about plus hardware wallets for transactions. We could perhaps split them into two separate issues too.

I have been putting together notes for validator security and HSMs are definitely part of it.

**Comment by jleni** [comment]
Looking forward to hearing more about this :)

**Comment by EdwardAThomson** [comment]
This issue is a candidate for our grants program. For details on how to apply, see your grants page: https://grants.web3.foundation

**Comment by 2075** [comment]
Hi there @EdwardAThomson , are there any developments regarding this or is it still in its infancy?

**Comment by EdwardAThomson** [comment]
Hey @2075 We have a team working on ledger integration. You can see the issues that Jaco referred to above. ^

There is at least one other hardware wallet team that we've funded. This will help to keep tokens cold, but it won't cover validation. The latter is a harder task and is subject to change since we are going to update the cryptography in our validation algorithm.

That said, we are generally open to new ideas and keen for proposals. Feel free to apply for a grant (see: http://grants.web3.foundation). You can reach out to us too at grants@web3.foundation.
