### ISSUE TITLE
Alternative Polkadot Runtime Generation (AssemblyScript) - RFP

### ISSUE THREAD

**Issue by dfishb** [w3f/General-Grants-Program#159]
Hello!

Currently, the only way to generate a Runtime is by using Rust along with Parity-built tools.  We would like to increase the choice of languages for developers to write these Runtimes and are **providing a grant for the development of a tool to generate WebAssembly Runtimes from AssemblyScript.**

For more information and for details on how to apply, please see the following document:
[Alternative Polkadot Runtime Generation (AssemblyScript) - RFP](https://docs.google.com/document/d/1HyIUW3sLNtU-89ZVSVBPEpEMqJ97oxjbIo85xOiRnBs/edit#)

Feel free to comment with any questions on the process. Questions of a technical nature can also be asked in the [Substrate Technical riot channel](https://riot.im/app/#/room/#substrate-technical:matrix.org).

**Comment by GregTheGreek** [comment]
Applying shortly!

**Comment by PascalPrecht** [comment]
Hey everyone,

I was wondering what's the status of this and wether there's a project/repo on GitHub that one could check out.

Thanks!

**Comment by dfishb** [comment]
> Hey everyone,
> 
> I was wondering what's the status of this and wether there's a project/repo on GitHub that one could check out.
> 
> Thanks!

It's still open so feel free to apply!

**Comment by PascalPrecht** [comment]
Hey @dfishb !

Unfortunately, I don't think I have the expertise to work on this by myself, but I'd be highly interested in contributing to the project.

@GregTheGreek you still up for making this a thing?

**Comment by lastmjs** [comment]
Status? Are applications still open?

**Comment by dfishb** [comment]
@lastmjs - We've received a couple of applications that we're in the process of considering but feel free to submit something! Ideally soon if possible :)
