### ISSUE TITLE
Meetup - Polkadot - Paris, France

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#18]
We are looking to invite people to help organise and co-host a Polkadot meetup in Paris, France.

**Comment by Cambrial** [comment]
Hey guys. We might be interested in co-hosting the Polkadot meetup in Paris. Which date did you have in mind?

**Comment by EdwardAThomson** [comment]
We don't have any date in mind, but rather we are open to discussion on it. We would love for the community to suggest a timeframe and then help us to make it happen. If you want to take the lead on this initiative for Paris that would be great!

We should be able to help with some sponsorship and hopefully be able to provide a speaker too.

Our current info on meetups is here:  https://github.com/w3f/Web3-collaboration/blob/master/meetups.md

**Comment by Cambrial** [comment]
Hey Edward,

That sounds great! Cambrial is definitely interested in taking the lead on that. I will get back to you in a few days with more information about what we envision for the event :) If that sounds interesting then we can set-up a quick call to go over it and move forward with the organization!

**Comment by EdwardAThomson** [comment]
Hey @Cambrial 

Sounds good. We can cover Paris and London in a call sometime soon. Looks like you have an interest in being involved in both / either. My colleague Josh also just replied in the London thread too. Feel free to reach out to him (or both of us, my email address is similar to his ;-) ).
