### ISSUE TITLE
Meetup - Polkadot - Sydney, Australia

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#19]
We are looking to invite people to help organise and co-host a Polkadot meetup in Sydney, Australia.

**Comment by anjj123** [comment]
Happy to help with this. I can also assist with inter-state meetups (Melbourne in particular has a big community worth exploring).

**Comment by ltfschoen** [comment]
I'm from Sydney, I'll be back there at some stage, happy to help!

**Comment by EdwardAThomson** [comment]
Hey Luke @ltfschoen, if you were able to present something at a Sydney meetup that would be great! I know Aeron is heading to Australia soon and is hopefully presenting in Melbourne mid-November, I fear he may not be able to make it to Sydney this time. However, it would be great to get someone there in 2019.

**Comment by dpnova** [comment]
I met Aeron in Sydney (I was mentoring at the blockathon).

We're super excited about polkadot and keen to help.

We run a meetup on the Gold Coast, which I expect to be too small to qualify for anything from the foundation, but perhaps there's ways we can be involved or help support meetups in the other major cities.

Cheers!

**Comment by EdwardAThomson** [comment]
Hey @dpnova ! Thanks for the interest.

There is always a chance that we can visit Sydney at some point. Hard to commit to anything right now, but I suspect there will be an opportunity this year.

The organiser for Melbourne (Terry, @bertstachios) is hoping to have more regular events and do promotion of all things Web3 in Australia. Whether we at W3F can do something to help support that is still under discussion. However, it is probably worth you both being in touch!

**Comment by bertstachios** [comment]
Hi @dpnova, I'm excited to hear your keen to hold Polkadot meetups!

I am based in Melbourne, but i'll help out any way I can and keep you in the loop for future Web3 / polkadot meetups that we're planning. Reach out to me on telegram, my username is @bertstachios and we can chat some more.
