### ISSUE TITLE
Meetup - Polkadot - Adelaide, Australia

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#20]
We are looking to invite people to help organise and co-host a Polkadot meetup in Adelaide, Australia.

**Comment by paulpounendis** [comment]
Fantastic. 

I prob base alot of the talk/meetup once it's organised on this.
https://www.youtube.com/watch?v=lIghiCmHz0U

**Comment by EdwardAThomson** [comment]
Great. Thanks for the interest Paul! We have a bunch of resources that we can supply to help kick start your meetups. Gav's London presentation is a good starting point!

We'd like to empower you to talk about Polkadot to local groups you participate in, and we are more than happy to help you organize events yourself. Ideally, we might be able to get a some people from Parity / W3F to come visit, but no guarantee at the moment. 

We have some recommended resources that are good as starting points:

- The interoperability presentation Rob gave at [TOA Berlin](https://www.youtube.com/watch?v=DTkWGJZPcz0).
- The Substrate [slide deck](https://slides.com/paritytech/) that Gav used for [EdCon](https://youtu.be/VsZuDJMmVPY?t=6h52m34s) and [Event Horizon](https://www.youtube.com/watch?v=iUMZyL5kTwc&t=3s).

**Comment by paulpounendis** [comment]
Thanks. Done and done.

**Comment by paulpounendis** [comment]
@EdwardAThomson Me and a few other people in Adelaide who are deep the industry are looking at running a big Blockchain conference in March/April, alongside a hackathon. Inline with you mentioning a more larger scope for an International tour for Polkadot, I think this type of tour is something that will be most worthwhile for you all.
