### ISSUE TITLE
RFP - Minimal Parachain Development Kit (PDK)

### ISSUE THREAD

**Issue by Noc2** [w3f/General-Grants-Program#204]
Hi everyone,

Currently, the only **Parachain Development Kit (PDK)** that exists is the combination of the Substrate blockchain framework and the cumulus extension, which is still in development. We would like to support the development of additional tools that will enable writing a parachain from scratch and connecting it to Polkadot.

For more information and for details on how to apply, please see the following document:
[RFP - Minimal Parachain Development Kit (PDK)](https://drive.google.com/file/d/1cMqhjj72yxlMiw99XaAxB3OhYTvVkWnA/view)

Feel free to comment with any questions on the process. We also welcome questions of a technical nature in the Substrate Technical riot channel.

**Comment by hskang9** [comment]
hey, I have a create-react-app+project-man development kit on substrate. I have mapped command for running substrate with the cli and trying to support Windows. If you have your parachain platform, I can add that in my development kit. If you want more detail, let's discuss.

**Comment by hskang9** [comment]
https://github.com/parachain-tracker/pyra

**Comment by hskang9** [comment]
here is the proposal WIP, you are welcome to join this project. https://github.com/w3f/Web3-collaboration/pull/205

**Comment by PascalPrecht** [comment]
If anyone applies for this here and wants to build a PDK in TypeScript, I'd like to contribute (for learning purposes).
