### ISSUE TITLE
Meetup - Polkadot - Bangalore, India

### ISSUE THREAD

**Issue by aj07** [w3f/General-Grants-Program#22]
Hy, I got chance to meet Jack in Ethindia during India's first Polkadot meetup. I wanted to organize further meetup of Web3 foundation for Bangalore and Delhi region.

I got grant from ETH Foundation to work on Solidity. Currently doing lots of research on Scalability and Polkadot, Parity Substrate.

We are already organizing meetups for Ethereum and Hyperledger ecosystem. We have lots of interest in Polkadot innovation. Wants to put our fellow developers to get involve as open source developer to Web3 Ecosystem

https://www.meetup.com/Hyperledger-Bangalore/
https://www.meetup.com/India-Blockchain-Cryptocurrency-Meetup/events/248888482/

Thanks,
Ankit
ankitblockchain3@gmail.com

**Comment by kggp1995** [comment]
Thanks for the pitch @aj07 .

Team, we'd love to connect the dots in India!!

**Comment by Josh0akley** [comment]
@aj07 thanks for reaching out. I have added you as a co-organiser for 'Polkadot - Bangalore' group. Feel free to get in touch when you're making plans for the next meetup, we'd be only to happy to help!

**Comment by kggp1995** [comment]
This should be nice!!

We are coming to the 6:30 event at Berlin Blockchain Week! It’d be nice to
talk more on this with the team there.
