### ISSUE TITLE
Meetup - Polkadot - Tucson, USA

### ISSUE THREAD

**Issue by tucsonblockchain** [w3f/General-Grants-Program#26]

**Comment by EdwardAThomson** [comment]
Thanks for showing interest in hosting a Polkadot meetup. In order for us to help you better, it would appreciate if you could add a few more details of what you are thinking (specifically for *this* meetup). We really want to make sure we can do the best thing for teams who want to build a better community.

I've included a template and some example responses in the following document:
[Examples](https://github.com/w3f/Web3-collaboration/blob/master/response-examples.md)

**Comment by EdwardAThomson** [comment]
So we have been talking about this meetup in the W3F HQ. We will be able to sponsor the pizza as requested. We would appreciate if you could create the event on the event on meetup.com and then post us the link. 

I think you are right to wait for the university to start back again in the new semester! Late October sounds good. We can also get you Polkadot presentation material.

**Comment by tucsonblockchain** [comment]
Mr. Thomas,
Thank you for getting back to me. And also for your ability to sponsor the
pizza!
https://www.meetup.com/Tucson-Blockchain-Developers
Our next meetup is in 2 days. Destry, who runs it is a doctorate in Astro
Physics, yet is Genesis Engineer at Unchained Capital
https://www.unchained-capital.com/
Unchained Capital is the sponsor of the Tucson Blockchain Developers
Meetup  and (Destry) they bring in several pizzas ($100 worth) each meetup
(very generous). Destry opened it up that if anybody wants to sponsor the
meetup, they will put up project on the slides and mention the project as
the sponsor of the event. Granted this is the Tucson Blockchain Developers
meetup. As you are aware I am looking at a stand alone Meetup for Polkadot
here in Tucson, yet it could be coordinated via Tucson Blockchain
Developers meetup, especially if you want to sponsor that event.
I can coordinate with Destry the images you want for the slides (or even
video) and sponsoring of the event or if you feel comfortable dealing with
him direct, I can get his contact info to you ASAP. He works out of a local
coffee house (coding) and he is generally prompt. We also have a slack for
backup.
Let me know how you wish to proceed. That's awesome and thanks.
If you sponsor this event, I will have the opportunity to prime the pump
with the Polkadot Meetup and see if anybody wants to help me and work in
coordinating for late October and perhaps dive into setting up a node,
after showing some video, and basically educate others on resources, Riot,
Telemetry, and setting up an account. At least that's the plan. And I do
think I can get some help from folks at Tucson Blockchain Developers.
I'll await your response.

Brent Woods
(520) 244-3733

**Comment by tucsonblockchain** [comment]
I spoke to Destry from the meetup and he's a bit busy this week as far as
prepping the slides, for sponsoring in 2 days, but he said if I introduced
him to Polkadot, could sponsor the next event (every 2 weeks so in about 16
days approx). Do you have an email? Or should I send him to the Polkadot
Watercooler for introduction?

Brent

**Comment by EdwardAThomson** [comment]
I just responded to you on Riot. We can chat there.
