### ISSUE TITLE
Meetup - Polkadot - Zürich, Switzerland

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#27]
This is issue is real, but I'm adding some example text to show how I'd like meetup issues to be created. :-)

* **What is the plan**: To organise a Polkadot meetup in Zürich. Currently, the plan is to have the first one on Wednesday 26th September at ETH Zürich. There will be a new meetup group created on meetup.com. The event will contain all the necessary details that the community will need to know.
* **How many people**: The first meetup is being organised by myself and Vasiliy (Crypto Valley Association).
* **Do you need help from W3F**: Provide team members to do a presentation on Polkadot would be appreciated. As this is a major city then it would be appreciated if funding were available to record this meetup.
* **Do you need help from the community**: Attendance would be greatly appreciated. As would some help to promote the event. :-)

New Polkadot Zürich meetup group: https://www.meetup.com/Polkadot-Zurich/

**Comment by EdwardAThomson** [comment]
Venue booked and date chosen.

**Venue**: ETH Zürich
**Date**: Wednesday 26th September
**Time**: 6pm - 10pm (this is how long we have the room for)

Speakers and exact topics to be confirmed.

**Comment by ptsankov** [comment]
Small correction: the room is available from 6PM - 9 PM. Catering / drinks can be hosted outside the room or at Polyterasse.

**Comment by EdwardAThomson** [comment]
The first of these events is now scheduled:

https://www.meetup.com/Polkadot-Zurich/events/254410078

**Polkadot Zürich**

Date: Wednesday 26th September
Time: 18:00 - 21:00

Venue:
ETH Zürich
Haupt Gebaude,
Room 1.2, Floor D.
Rämistrasse 101
8092 Zürich

**Comment by EdwardAThomson** [comment]
Potentially going to organise something for Zug in January. More details to follow.
