### ISSUE TITLE
Meetup - Polkadot - Munich, Germany

### ISSUE THREAD

**Issue by fkbenjamin** [w3f/General-Grants-Program#32]
My name is Florian and I am one of the founders of [Staking Facilities](http://stakingfacilities.com), a Munich-based consensus infrastructure provider. We operate secure, reliable and performant Proof of Stake infrastructure for a variety of DLT/Blockchain protocols. Besides that, we are also hosting meetups for our local community and already had the pleasure to hear talks from projects like **_Dfinity, Rchain & Foam._**
We've already been in contact with Jack  (@jplatts12) about organizing a Polkadot Meetup here in Munich. A talk from Polkadot at one of our events would be a true enrichment for us and the community.

- **What is the plan:** To organize a Polkadot meetup in Munich. We are flexible on the date but currently would favor sometime in October of this year. There is already a [meetup group](https://www.meetup.com/de-DE/Staking-Facilities/) available and an email list (100+) where we invite local, interested people to our events. We will provide all the necessary details to the community.

- **How many people:** We have a well-organized team for our meetups that also includes an awesome camera guy who creates professional videos of our events.
**_Foam & Rchain Teaser:_** https://www.youtube.com/watch?v=m3DWGffNXKE
**_Foam & Rchain Full Video:_** https://www.youtube.com/watch?v=1WH1kdMAQ8s
**_Dfinity Full Video:_** https://www.youtube.com/watch?v=p6CVRNT3k1E

- **Do you need help from W3F:** A team member to do a presentation on Polkadot would be necessary. We are able to pay for the event (location, catering & video) on our own, but it is quite costly and we would appreciate any kind of support/funding. Our community loves swag, so if we could get some t-shirts and stickers, that would be awesome!

- **Do you need help from the community:** Attendance would be greatly appreciated. As would some help to promote the event. 😇

**Comment by EdwardAThomson** [comment]
Awesome! Sounds like you guys are meetup pros already. :-) Jack did mention that he spoken to you guys, but we appreciate you adding an issue to our repo.

I'm pretty sure we will be able to provide some help with the event. However, before I can promise anything the comms / meetup team are due a catch up to make sure we have a robust process in place for handling this.

**Comment by fkbenjamin** [comment]
No worries, we can be patient. If you require any further information from us, you can write us here or contact us directly. Jack has my contact information. However, I saw that there is an application form. Should I also enter our information there?

**Comment by EdwardAThomson** [comment]
Yeah, it is probably worthwhile filling in the application form. It helps us to keep all the information on teams in one place. :-)
