### ISSUE TITLE
Meetup - Polkadot - Denver, USA

### ISSUE THREAD

**Issue by charleyhine** [w3f/General-Grants-Program#33]

**Comment by EdwardAThomson** [comment]
@charleyhine Hey!

Thanks for showing interest in hosting a Polkadot meetup. In order for us to help you better, it would be appreciated if you could add a few more details of what you are thinking (specifically for this meetup). We really want to make sure we can do the best thing for teams who want to build a better community.

I've included a template and some example responses in the following document:
[Examples](https://github.com/w3f/Web3-collaboration/blob/master/response-examples.md)

We have an application form that helps us to find out more about your initiative. Some more details can be found here:
[meetups](https://github.com/w3f/Web3-collaboration/blob/master/meetups.md)

We have also just published a guide on hosting meetups that you may find helpful:
[how to host a meetup]https://github.com/w3f/Web3-collaboration/blob/master/howtohostameeup.md
