### ISSUE TITLE
Meetup - Polkadot - HangZhou, China

### ISSUE THREAD

**Issue by ghuun** [w3f/General-Grants-Program#37]
My name is jiangpeng He who is the organizer from [Crypto Geek](http://www.mimajike.com/), a blockchain technology enthusiasts community. Our community was set up by engineers from Alibaba and other famous blockchain companies. We hosted hundreds meetups for the blockchain enthusiast in china, at present, we have more than **2,000 engineers&investors** members and **80,000 blockchain enthusiast members** and are the largest blockchain technology community in Hangzhou, China. We had the pleasure to attend many meetup about Polkadot and are very interested in it.In addition, we also  would like to host one technical  Meetup for our members about Polkadot recently in hangzhou.

- **What is the plan:** To organize a polkadot meetup in October of this year in hangzhou,china. Our community already have this meetup group available(**50+ technical developers of Alibaba and Zhejiang University** ) where we invite local, interested members to this event. we will invite  @yuelipeng, @jiangfuyao(0xthreebody) and @sorpaas as the speaker who will sharing the idea of the existing technologies and how to develop over it , such as : wasmi virtual machine, Substrate technology, Substrate-based development ([ChainX](http://www.chainx.org/)), and so on.

- **How many people:** we have a professional team that has organized a lot of meetups.As The support from our marketing, media, public relations, investment and other departments.

- **Do you need help from W3F**:if possible, we’d like a team member of Polkadot to do a presentation for us, and if not, its also would be very helpful to have some presentation material. Since it is quite costly and we would appreciate any kind of support/funding. And if we could get some t-shirts and stickers, that would be great!!

Finally I want to say that Crypto geek community represents our technologists members and the Polkadot technical evangelist is willing to establish the Polkadot Chinese community, and we also hopes we can achieve long-term good cooperation relations with W3F. we are capable of doing this well and we are confidence to spread polkadot to all tech enthusiasts in China.

We are looking forward to your reply！

**Comment by yuelipeng** [comment]
Welcome community developers in Hangzhou to come

**Comment by EdwardAThomson** [comment]
Great! That was a perfectly written post. Perhaps the best of any we've had so far in this repository. :-)

We are able to provide presentation material as a minimum, for example, we have some presentation material online already although we can also alternatives. See the material at the end of the following document: [Meetups](https://github.com/w3f/Web3-collaboration/blob/master/meetups.md)

Most of the Polkadot material that we have is fairly high level. However, we are getting a lot of requests to do a technical workshop, so this is something that we will start preparing soon.

We could probably provide a speaker. We intend to be doing a lot of meetups next year and that would include coming to China. I don't believe of the dates have been fixed yet, but we can try to coordinate seeing many Chinese cities in the same trip.

I was about to ask you to fill in the Meetup Collaboration form, but it seems you have already done that!!! Fantastic! :-D  

I need to chat with my colleague @Josh0akley and then we will get back to you. We are working together on Polkadot's global meetups.

**Comment by ghuun** [comment]
I am so sorry I might haven’t reply on time, since it’s national day in China from 01-07/Oct. Thanks for your reply and encouragement!! we indeed take this meet-up very seriously. there have some questions that I need to confirm with you:
1. You replied last time that you could probably provide a speak? who will be the recommended speaker from Polkadot? he will participate in what ways? Will he come to China to join this meet-up? or just online meet-up? 
2. is there have possible to get any kind of support (funding or tokens or swags?) how and when to get it?

please confirm as soon as possible. we hope it can soon be finalized so we can have more time to prepare and arrange.If the W3F has any further Suggestions, please let me know. I suggest that we can discuss more details through email, twitter or wechat.

**Comment by ghuun** [comment]
At the same time, we believe that this meet-up is the start of our cooperation in the future. As for Polkadot's next year ‘s China trip plan, we hope that we can get the opportunity to help Polkadot to host meet-ups in China.

**Comment by EdwardAThomson** [comment]
Hi @ghuun 

Many thanks for the continued interested! Apologies for my delayed response, currently on vacation for a couple of days.

> 1. You replied last time that you could probably provide a speak? who will be the recommended speaker from Polkadot? he will participate in what ways? Will he come to China to join this meet-up? or just online meet-up?

I just messaged you on Riot. Apologies for the delay in responding here.

We will likely provide a couple of people from  the combined W3F and Parity teams. They will visit China and will come with presentations, or with material for a workshop. It would depend on what type of events we are doing.

Obviously, we will let you know when we are coming once we have an idea. Hopefully early in 2019!

We are also discussing online webinars / workshops too.

> 2. Is there have possible to get any kind of support (funding or tokens or swags?) how and when to get it?

Absolutely. We can generally cover room costs and video costs. Also for snacks. We can also help with swag (e.g. t-shirts). All of this we can coordinate closer to the event. What is likely to happen is that we will organise what needs to be done and make the payments. Where we rely upon locals is for the knowledge in finding the best venues, connecting with the right people who can help, and then helping on the day of the event.

> please confirm as soon as possible. we hope it can soon be finalized so we can have more time to prepare and arrange. If the W3F has any further Suggestions, please let me know. I suggest that we can discuss more details through email, twitter or wechat.

Fortunately, we still have a few months to go! We will definitely coordinate ahead of time!

**Comment by EdwardAThomson** [comment]
The first event has been organised and announced. See details here: http://www.huodongxing.com/event/9461774172100

Thanks for organising!

**Comment by liangping** [comment]
i will join you next time
