### ISSUE TITLE
Meetup - Polkadot - Melbourne, Australia

### ISSUE THREAD

**Issue by bertstachios** [w3f/General-Grants-Program#39]
I'd like to plan a monthly Polkadot meetup in Melbourne, Australia. Target date for the first one will be mid November 2018.

Topics will revolve around education, high level technical overviews, how to set up a validator node to participate in the test net etc.

I'm a noob learning rust so I can contribute to the project and eventually build parachains on Polkadot. One of my goals is to create a beginner friendly meetup environment where we can learn together as Polkadot is incredibly exciting but highly technical. Of course people of all skill levels will be welcome as I'd like to foster a community of learning and good vibes. 

Anyone interested in contributing/collaborating for the Melbourne meetup - please let me know.

**Comment by EdwardAThomson** [comment]
Hey @bertstachios, it's great to hear from you. It sounds like you have a solid plan for Melbourne too. We are happy to support the best we can. There is some presentation material available, plus I'm looking to add another presentation soon (videos of that coming soon!). See the current material at the end of the following document: [Meetups](https://github.com/w3f/Web3-collaboration/blob/master/meetups.md)

I'm also happy to do a hangout sometime to chat about this too.

It is definitely possible for us to send W3F / Parity folks to Australia but we just need to plan ahead and try to make the biggest impact we can. :-)

Let me ping @anjj123, he said he is interested in helping with Sydney and Melbourne. Also I will ping @paulpounendis as he is interested in organising something in Adelaide. I appreciate that it may not be so easy to travel, but perhaps you guys will be able to meetup one day. :-) We are building up quite a list of strong community members in Australia which is awesome. :-D

Sydney issue: https://github.com/w3f/Web3-collaboration/issues/19
Adelaide issue: https://github.com/w3f/Web3-collaboration/issues/20

**Comment by bertstachios** [comment]
Hey @EdwardAThomson, cheers for the reply. Lets lock in a time to do a hangout and get the first Melbourne meetup underway! Aeron potentially coming down in November is perfect timing - so if he's cool to do it and the stars align - lets schedule it in. 

How many people do you need at a meetup to make it worth your while to come down? I'm really excited so I'll make sure we get the numbers to justify a trip down under.

**Comment by EdwardAThomson** [comment]
Since Aeron is travelling down there anyway there isn't a huge pressure for a massive audience. I believe he has already booked his travel. My colleague @Josh0akley will be coordinating with you and the community down there to try and get a meetup constructed.

In the future, we'd try to optimise visiting Australia with other countries on that side of the world I think. That way there is a less pressure for a huge audience at each individual meetup. If we only travelled to from Europe to Aus for a single meetup then it would need to be for a mega developer fest.

The meetups we've had so far have ranged from about 50 - 100. Obviously, 40 developers is better than 100 ICO investors, so quality is definitely a huge factor.

Going to keep things in email! That will help us to focus and coordinate with the rest of the Aussie community together. This is definitely exciting times! :-)

**Comment by bertstachios** [comment]
Meetup locked in for 15th November @ 6pm @ RMIT University

https://www.meetup.com/Polkadot-Melbourne/events/255816139/

**Comment by pkrasam** [comment]
@bertstachios @EdwardAThomson @Josh0akley @anjj123 @paulpounendis

Thanks for organizing this meetup. I have been experimenting with Polkadot and Substrate for a little while now. I am currently running a few nodes to support BBQ Birch network.

I live between Geelong and Torquay and would love to organize a meetup here and also help you gents in growing our local Polkadot/Substrate community, developer talent and potentially build some interesting stuff.

Keen to hear your thoughts on how I can get involved?!

Sidebar: Thank you @gavofyork

**Comment by jplatts12** [comment]
Polkadot Melbourne was a success! This is an amazing example of a purely community led meetup. Thank you to all who contributed @bertstachios @paulpounendis @pkrasam @anjij123 

View the members and videos here: https://www.meetup.com/Polkadot-Melbourne/
