### ISSUE TITLE
Project Saito's GitHub Link 404 Not Found

### ISSUE THREAD

**Issue by treasersimplifies** [w3f/General-Grants-Program#391]
I accidentally found that Saito( granted in 2020Q4-Wave8 )'s GitHub link(https://github.com/saito-lite) is 404 Not Found.

**Comment by treasersimplifies** [comment]
> I accidentally found that Saito( granted in 2020Q4-Wave8 )'s GitHub link(https://github.com/saito-lite) is 404 Not Found.

maybe it's private?

**Comment by Noc2** [comment]
Thanks. I just updated the link: https://github.com/SaitoTech, but I’m not sure saito already started to work on the project. You can find the application here: https://github.com/w3f/Open-Grants-Program/blob/master/applications/saito-game-protocol-and-engine.md  At least so far they haven’t submitted a milestone.
