### ISSUE TITLE
Create and run a node cluster service for Polkadot

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#43]
We would like someone to create and run a scalable RPC service for Polkadot. This would be a service that is elastic and can scale with the number of requests.

Features:
* Super stable RPC end point.
* Distribute requests appropriately.
* Spin up new resources as need.

We'd this service to work with the existing testnets (and to continue to work with testnets in the future). Eventually the service should support the main network at launch.

While running your own node is safer and something we want to promote. It is also important to grow the ecosystem and try to reduce the barriers to entry.

**Comment by EdwardAThomson** [comment]
This issue is a candidate for our grants program. For details on how to apply, see your grants page: https://grants.web3.foundation

**Comment by EdwardAThomson** [comment]
Hey @jpzk 

This issue is available for grant funding: i.e. for an external team to build something. We aren't planning to build this internally.

If you would like to apply for money to help build this then you can follow the link above and read about how to make a gran application. This has proven our most popular topic by far! (quite a few inquiries came in privately). So far, no money has been awarded for this issue yet.

Whether you can help another team build something, that is a good question but you'd have to wait for them to start building.

**Comment by prastut** [comment]
@EdwardAThomson would you be able to update this thread on developments on this issue?
