### ISSUE TITLE
Meetup - Polkadot - Hong Kong, Hong Kong S.A.R.

### ISSUE THREAD

**Issue by blokaly** [w3f/General-Grants-Program#44]
Hi, my friend and I would like to organise and co-host the Polkadot meetup in Hong Kong. I'm working at a FinTech startup involved in the crypto trading and investment business. We are R3 partner and member of HyperLedger. Personally I've been also actively participating the Ethereum meetups since it started and met Vitalik and Gavin several times. I haven't organised any meetup yet but my friend is the organiser of HyperLedger meetup here in HK and we would run the Polkadot meetup together.

I've been looking for cross-chain technologies for a while and had read Polkadot's white paper. I think Polkadot will be one of the promising options, so would like to host meetups here in HK to learn more about it and facilitate the adoption of it in our society, initially from the tech perspective and later on will extend to the business side, such as how to achieve interoperability by using Polkadot together with other public and permissioned chains, and what the benefits it brings to the enterprises and financial institutions.

**Comment by EdwardAThomson** [comment]
Hey @blokaly that would be great! Hopefully we are able to get some of our speakers to China to attend one of your meetups. It should be possible in 2019. Keep an eye out for more details.

I would suggest that you join the Watercooler chat channel if you haven't already. There is where the main source of activity is happening:  https://riot.im/app/#/room/#polkadot-watercooler:matrix.org

**Comment by blokaly** [comment]
Thanks @EdwardAThomson 
Have joined the Watercooler channel and will chat you over there...

**Comment by ansonla3** [comment]
hey @blokaly , I am also from Hong Kong, and would love to co-host / build Polkadot meetup community in Hong Kong, do you have any contact methods ?

**Comment by blokaly** [comment]
> hey @blokaly , I am also from Hong Kong, and would love to co-host / build Polkadot meetup community in Hong Kong, do you have any contact methods ?

@ansonla3 please join https://www.meetup.com/Polkadot-Hong-Kong/ and we can connect from there.
Thanks.

**Comment by jplatts12** [comment]
@blokaly and @ansonla3 have you guys made any progress in hosting the first Polkadot HK meetup? We won't be able to send a speaker until April, but we could video chat in to answer questions, do an online AMA, or provide funding / resources for you guys to organize your first event! Reach out to jack@web3.foundation if this sounds interesting.

**Comment by ansonla3** [comment]
hey @jplatts12 , actually there was a polkadot meetup in 12/8 that was hosted by Ethereum Hong Kong, which gavin has come to Hong Kong to give an overview of polkadot.
And @blokaly and I will have a short conversation how we collaborate very soon.

**Comment by blokaly** [comment]
Thanks @jplatts12 @ansonla3 yep we had one already and will do one in the new year as I mentioned to Gavin during the meetup. Will reach out later for more tech resources. Have a wonderful holiday season!
