### ISSUE TITLE
Meetup - Polkadot - Toronto, Canada

### ISSUE THREAD

**Issue by Mikerah** [w3f/General-Grants-Program#45]
Hi,

I run the University of Toronto Blockchain Group, a student club at the University of Toronto. We would love to start collaborating with the Web3 Foundation for events in Toronto.

A little about me:
I am a sharding implementer involved in the Biweekly Eth2.0 talks and I work at a Toronto company called ChainSafe Systems. The founder, Aidan Hyman, is friends with Afri from Parity Technologies and is heavily involved in blockchain.

**Comment by EdwardAThomson** [comment]
Hi @Mikerah , sincere apologies for the slow reply. The past 2 weeks have been busy with W3S and now DevCon. I met with both Aidan and Elizabeth though and had some great conversation with them about possible future directions (in tech). Having meetups in Canada would be great too.

Are you in our Riot chat channel?

https://riot.im/app/#/room/#polkadot-watercooler:matrix.org

**Comment by Mikerah** [comment]
@EdwardAThomson I just joined. Let's move the conversation there.

**Comment by mehranhydary** [comment]
Hey all! Can I get in on this too :)

**Comment by jplatts12** [comment]
Polkadot Toronto v1 was a success! https://www.meetup.com/Polkadot-Toronto/events/256671683/
