### ISSUE TITLE
Meetup - Polkadot - Singapore

### ISSUE THREAD

**Issue by jazken** [w3f/General-Grants-Program#46]
Hi, I am Kenneth, currently a blockchain enthusiast in Singapore. Currently, my team and I run a community meetup and workshop with Blockstack. We have been hosting meetups in partnerships with various other local communities (e.g. Ethereum Singapore, Singapore University of Social Sciences etc.) this year serving thousands of members.

What is the plan: 
To organize a Polkadot meetup in December/January of 2018/2019 in Singapore. We intend to work with other local communities (e.g. Ethereum Singapore, GDG Singapore, etc.) to share more of the technicalities of polkadot with local developers who might be interested to work on parachains between their technology and others.

How many people: 
We are a small team of two who will be keen to recruit anyone developers/keen learners who are enthusiastic about blockchain technology like us.

Do you need help from W3F: 
We will prefer is a team member of Polkadot will be able to help us with the presentation or queries especially when it comes to technical implementations. If not, it will be great to have some presentation material. We will appreciate any kind of support/funding/swag such as t-shirts or stickers will be awesome.

We hope to bring polkadot technology to more developers and users in our region. Looking forward to your reply.

**Comment by EdwardAThomson** [comment]
Hi @jazken. Great to hear from you. Anything you can organise yourself is welcomed. We might be able to send team members next year, but hard to commit to something before year's end.

Are you in our Riot chat channel?

https://riot.im/app/#/room/#polkadot-watercooler:matrix.org

**Comment by ngerald51** [comment]
Hi Edward, 'Im with @jazken and im in the riot channel.

Maybe we can arrange something tentative beginning of next year? also do you have any plans to drop by asia some time soon? Thanks

**Comment by EdwardAThomson** [comment]
There are plans in the works for some of our team to be in Beijing and Korea in a few weeks. Still waiting on confirmation. They are travelling for conferences and may do some meetups since they are already there. Don't think there is slack in their schedule to travel elsewhere though.
