### ISSUE TITLE
Meetup - Polkadot - Tokyo, Japan

### ISSUE THREAD

**Issue by jplatts12** [w3f/General-Grants-Program#5]

**Comment by SotaWatanabe** [comment]
Hey @EdwardAThomson, 
Nice to see you. I am glad that I could find this issue. My name is Sota Watanabe, a founder of Staked Technologies Japan. Currently, we are making blockchains by using Substrate. 

I have organized the first meetup you mentioned above and we have the 2nd meetup this month. 
- Substrate Workshop #1 (https://neutrino.connpass.com/event/121572/）

I am planning to have a Substrate/Polkadot meetup at least once in a month. Let you know when we hold meetups. Next time, we would like Web3 devs to present Polkadot and Substrate.

Also, I have talked with Rory and Jack and became one of the ambassadors.

**Comment by EdwardAThomson** [comment]
Hey @SotaWatanabe 

Thanks for reaching out. I know John has reached out to you privately, but I just wanted to say add my own 'welcome' message.

Obviously, we are thrilled that you will be holding monthly meetups. It is great to see these community initiatives. As always, feel free to share your meetup links in r/dot (our official sub) or even r/polkadot_market (fan sub).

Cheers!

**Comment by SotaWatanabe** [comment]
@EdwardAThomson Thank you for your support. I am happy to contribute to the community. Let me know if there is anything I can help^^

**Comment by SotaWatanabe** [comment]
Cosmos vs Polkadot
https://neutrino.connpass.com/event/132916/

Substrate Workshop 5/23
https://bdevux.connpass.com/event/130567/

Plasma and Substrate 4/17
https://neutrino.connpass.com/event/127035/

Substrate meetup 3/18
https://neutrino.connpass.com/event/121572/

**Comment by SotaWatanabe** [comment]
Polkadot governance was written by @masaki
https://medium.com/unchained-tokyo/polkadot-governance-9853279f4a76

Slide decks (Governance, Sub0 Summit, Substrate, Plasm)
https://medium.com/unchained-tokyo/%E7%AC%AC2%E5%9B%9Esubstrate-polkadots%E5%8B%89%E5%BC%B7%E4%BC%9A%E9%96%8B%E5%82%AC%E3%83%AC%E3%83%9D%E3%83%BC%E3%83%88-c55c9dbcc2cc
