### ISSUE TITLE
Meetup - Polkadot - Rotterdam, Netherlands

### ISSUE THREAD

**Issue by jplatts12** [w3f/General-Grants-Program#6]
A Rotterdam event has been tenatively announced, please see: https://www.meetup.com/Polkadot-Netherlands/

**Comment by EdwardAThomson** [comment]
The first meetup of Polkadot Netherlands has been announced: 

## Polkadot, Substrate & Web3
The inaugural Polkadot Netherlands meetup is a joint initiative by Web3 Foundation and #ETHDEVNL (http://ethereum.nl). This meetup will be hosted by our very kind friends at [Blocklab] in Rotterdam (right next to Rotterdam Central Station). We hope to see you all on Tuesday October 2nd (17:30 - 22:30).

This meetup will be themed around WEB3. We will explore Polkadot, Substrate and Web3 which will help materialize a new vision for the internet itself.


**Date**: Tuesday, October 2, 2018
**Time**: 5:30 PM to 10:30 PM
**Venue**: CIC Rotterdam [A-Building], Stationsplein 45 | 4th Floor · 3013 AK, Rotterdam

https://www.meetup.com/Polkadot-Netherlands/events/253164982/
