### ISSUE TITLE
Request for Substrate/Polkadot Rust Bootcamp

### ISSUE THREAD

**Issue by burrrata** [w3f/General-Grants-Program#74]
Tezos has a really cool looking bootcamp, that's free, and accessible to anyone with a computer and internet connection. It's pinned very nicely to the top of their really cool subreddit:
- https://www.reddit.com/r/tezos/
- https://medium.com/tezoscommons/announcing-tezos-capstone-2d5631b99a2

Is Web3 planning on doing anything similar? Because that would be cool... really really cool. It would also be relatively cheap for the value returned because:
- MOOCs are 1 => many,
- Rust just updated to the 2018 edition,
- and the program could be valuable not just to bootstrap the Polkadot ecosystem, but for years to come as people from other blockchains get interested, but need help getting over the Rust barrier (macros!, Traits, 'lifetimes)

**Comment by jrmoreau** [comment]
Are you referring to [](https://tomi.institute/)?

**Comment by burrrata** [comment]
@jrmoreau Added a link to the description of the Tezos bootcamp. Does that help explain what I'm referring to?
