### ISSUE TITLE
Meetup - Polkadot - Philadelphia, USA

### ISSUE THREAD

**Issue by adnantium** [w3f/General-Grants-Program#82]
The [Philadephia Ethereum meetup](https://www.meetup.com/Philadelphia-Ethereum-Meetup/events/258251527/) recently arranged a session on the PolkaDot Whitepaper that got positive feedback and interest from the group. This is a great opportunity to build on that to create a larger community focussed on PolkaDot & Substrate.

* **Plan**: Meetup group for PolkaDot (and related Substrate etc.) in Philadelphia PA USA
   * Help people see the potential of blockchain tech beyond btc, eth and cryptocurrency speculation.
   * Enable discussions and expand understanding on technology decentralization and its larger future impacts
* **How many people**: ~20 Would be a good start.
* **Help from W3F**: 
   * Help getting the word out. 
   * Connections to speakers interested in presenting future meetups. 
   * Any content and presentation material we can reuse & extend.
   * swag
* **Help from community**: Advice on good topics to focus on for initial meetups while the community is starting up and building awareness of what PolkaDot is

**Comment by EdwardAThomson** [comment]
Hey @adnantium that sounds great!

Have you checked out our meetup page? It has a lot of useful material (incl presentations): https://github.com/w3f/Web3-collaboration/blob/master/meetups.md

Helping to get the word out is fairly easy: e.g. r/dot and twitter.

A good first step is to chat with my colleague Rory about our ambassador program. That is something we are still putting together but we are trying to get community members to be engaged in our online community as well as organising events.

**Comment by theroryshow** [comment]
@adnantium First off thanks for reaching out. 
I always recommend keeping it simple with your first meetup. What Polkadot is, who the team is, what problem are they trying to solve, how is their approach unique, and the latest news and developments. That should give you a good 15-20 minute presentation and leave plenty of time for questions, which can be directly relayed to myself or the team to follow up on. 

We also have an Ambassador program which allows those hosting meetups the opportunity to directly interact with the team, ask questions, and take a more active role in the community. If that sounds interesting please contact me at rory@web3.foundation and we can discuss in further detail. 

I'm also happy to provide any support or advice you might need.

Rory

**Comment by Web3Foundation** [comment]
@adnantium we'd love to help support your meetup in Philadelphia and glad to help on the mentioned ideas and would be excited to jump on a call with you about it!

Please reach out to me at chris@web3.foundation so we can take a few minutes to chat about it.
