### ISSUE TITLE
Open Source Node Explorer

### ISSUE THREAD

**Issue by EdwardAThomson** [w3f/General-Grants-Program#9]
We would like to collaborate with teams in order to bring about an open source node explorer for the Polkadot network.

**Take inspiration from Ether Nodes:**
https://www.ethernodes.org/network/1

**Useful information to display:**
Client types, client versions, locations and any other info. This will require some fancy node crawling to figure out whats going on.

**Difference between a node explorer and a block explorer:**
A node explorer is looking at the network, while block explorers are looking at the data stored within the blocks of the chain itself.

**Comment by aj07** [comment]
I would like to work on this project along with my other teammates. 
Background: Myself, Ankit is working in Blockchain ecosystem from last 2.5 years. I had worked with Red Hat on Distributed System (GlusterFS) and on RPC protocol in GSoC. Also, I was the grantee from Eth Foundation in wave1 to work on solidity.  Previously we have created some node explorer for quorum project.
We would love to work on this.

If you suggest we will share the few mock ups and design for node explorer for it in few days and start the discussion on riot.

**Comment by EdwardAThomson** [comment]
That sounds awesome! :-) We can try to help you coordinate with the right people. Obviously you can find the devs in the usual watercooler chat, otherwise you can also try in [Substrate Technical](https://riot.im/app/#/room/#substrate-technical:matrix.org). 

I'd say dive right in! Feel free to drop thoughts here, or you can mail them over.

**Comment by aj07** [comment]
Thanks @EdwardAThomson  I have been active on riot. Please , put me touch with right person.

**Comment by EdwardAThomson** [comment]
Cool. Let me reach out to someone at Parity to find out who the best person is for you to speak to. If you don't hear anything from Parity by end of next week then drop me a message here or on riot (@edwardt:matrix.org).

**Comment by emielvanderhoek** [comment]
@EdwardAThomson please explain what sets a 'node explorer' apart from a 'block explorer'. I find that I am having difficult making a hard distinctions and explain this to ppl. It may be a spectrum and a bit blurred... Appreciate the input!!

**Comment by EdwardAThomson** [comment]
Something along the lines of https://www.ethernodes.org/network/1

Client types, client versions, locations and any other info. This will require some fancier node crawling to figure out whats going on.

A node explorer is looking at the network, while block explorers are looking at the data stored within the blocks of the chain itself.

**Comment by EdwardAThomson** [comment]
This issue is a candidate for our grants program. For details on how to apply, see your grants page: https://grants.web3.foundation
