### ISSUE TITLE
Meetup - Polkadot - Beijing, China

### ISSUE THREAD

**Issue by bobjiang** [w3f/General-Grants-Program#92]
## introduction
I am Bob Jiang, and run a blockchain technical community in China now. [HiBlock](http://hiblock.one) focuses on meetup/workshop/hackathon, and have 6k members now.

## What is the plan:
We are planning to have polkadot meetup in Beijing by the end of May. And if possible, once per month to introduce technical view from polkadot.

## Number of people on your team:
There are 5 core members (part time) from hiblock, based in Beijing, Shanghai, Shenzhen, Xi'an etc.

## Do you need help from W3F:
speakers, or presentation slides, etc.

## Do you need help from the community:
Not sure, don't know for now.

**Comment by ansonla3** [comment]
@bobjiang do you have wechat ? we can have a chat see whether how we can help you ? ;)

**Comment by EdwardAThomson** [comment]
Hi @bobjiang ! Welcome!

We have presentation material here: [Link](https://github.com/w3f/Web3-collaboration/blob/master/meetups.md#presentation-material). You are free to use that!

We will be sending team members to China this year but I don't recall if we have any exact dates yet. We do also now have a team member based Hong Kong who will be reaching out soon! @ansonla3 

Naturally, we'd also recommend inviting the great community teams we have based in China: e.g. Polkawallet (who you know), ChainX, and I'm hearing of more teams coming forward!

**Comment by bobjiang** [comment]
I know the founder of Polkawallet and ChainX, thanks for your reply.

Hi @ansonla3 I added you by wechat in wechat group.

**Comment by jiangfuyao** [comment]
@bobjiang We should form a WeChat group to talk about this.

**Comment by ansonla3** [comment]
@jiangfuyao @bobjiang good, let's move there
